### PR TITLE
Update mesh.rs, fix https://github.com/unlimitedbacon/stl-thumb/issue…

### PR DESCRIPTION
**Pull request by shufanshijie**
…s/67

### CODE REVIEW

**Comment by unlimitedbacon** [comment]
Thank you!

**Comment by gyscos** [comment]
This turned the default render color to red, was that expected?

**Comment by unlimitedbacon** [comment]
That was not intended. I thought I had changed it back but I guess not.

**Comment by gyscos** [comment]
There's a PR out to revert it: #88

**Pull request merged**
