### PR TITLE
Add support for 3mf files

### PR DESCRIPTION
**Pull request by gyscos**
This PR adds basic support for 3mf file using the threemf crate.

It merges all models in the 3mf file, and recalculates normals.
It does not attempt to reuse vertices from different triangles.

### CODE REVIEW

**Comment by gyscos** [comment]
Fixes #48

**Comment by gyscos** [comment]
Note that `threemf` has a compatibility issue with some 3mf files, in particular the ones exported by onshape.
We may want to wait until https://github.com/hannobraun/3mf-rs/pull/54 is merged, as it'll be a breaking change.

**Comment by unlimitedbacon** [comment]
This is fantastic! Yes, lets wait a bit and see if that change to threemf gets merged.

**Comment by gyscos** [comment]
I added a commit to adjust for the upcoming breaking change in threemf - currently tracking the git repo. Once they release 0.6.0 (maybe next week) we can update this PR to use that.

**Comment by gyscos** [comment]
`threemf` has now released 0.6.0 with the required fix, and I updated this PR to use this new version. Everything should be ready to merge.

Note: it may make sense to rebase https://github.com/unlimitedbacon/stl-thumb/pull/92 after this PR and merge it if possible, as it will certainly help to keep the codebase up to date.

**Pull request merged**
